# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("113")
        Form.resize(890, 723)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.DatePicker = DatePicker(Form)
        self.DatePicker.setObjectName("DatePicker")
        self.gridLayout.addWidget(self.DatePicker, 5, 2, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.SearchLineEdit = SearchLineEdit(Form)
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.gridLayout.addWidget(self.SearchLineEdit, 9, 2, 1, 3)
        self.SubtitleLabel = SubtitleLabel(Form)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout.addWidget(self.SubtitleLabel, 1, 1, 1, 1)
        self.DateEdit = DateEdit(Form)
        self.DateEdit.setObjectName("DateEdit")
        self.gridLayout.addWidget(self.DateEdit, 4, 4, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.Slider = Slider(Form)
        self.Slider.setOrientation(QtCore.Qt.Vertical)
        self.Slider.setObjectName("Slider")
        self.gridLayout.addWidget(self.Slider, 5, 5, 4, 1)
        self.ZhDatePicker = ZhDatePicker(Form)
        self.ZhDatePicker.setObjectName("ZhDatePicker")
        self.gridLayout.addWidget(self.ZhDatePicker, 6, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.CalendarPicker = CalendarPicker(Form)
        self.CalendarPicker.setObjectName("CalendarPicker")
        self.gridLayout.addWidget(self.CalendarPicker, 5, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 10, 2, 1, 1)
        self.TimePicker = TimePicker(Form)
        self.TimePicker.setObjectName("TimePicker")
        self.gridLayout.addWidget(self.TimePicker, 6, 3, 1, 2)
        self.TimeEdit = TimeEdit(Form)
        self.TimeEdit.setObjectName("TimeEdit")
        self.gridLayout.addWidget(self.TimeEdit, 4, 3, 1, 1)
        self.IndeterminateProgressRing = IndeterminateProgressRing(Form)
        self.IndeterminateProgressRing.setObjectName("IndeterminateProgressRing")
        self.gridLayout.addWidget(self.IndeterminateProgressRing, 3, 1, 2, 1)
        self.RadioButton = RadioButton(Form)
        self.RadioButton.setObjectName("RadioButton")
        self.gridLayout.addWidget(self.RadioButton, 8, 1, 1, 1)
        self.SpinBox = SpinBox(Form)
        self.SpinBox.setObjectName("SpinBox")
        self.gridLayout.addWidget(self.SpinBox, 8, 3, 1, 1)
        self.LineEdit = LineEdit(Form)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout.addWidget(self.LineEdit, 3, 3, 1, 2)
        self.AMTimePicker = AMTimePicker(Form)
        self.AMTimePicker.setObjectName("AMTimePicker")
        self.gridLayout.addWidget(self.AMTimePicker, 7, 1, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 6, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SubtitleLabel.setText(_translate("Form", "示例"))
        self.RadioButton.setText(_translate("Form", "Radio button"))
from qfluentwidgets import AMTimePicker, CalendarPicker, DateEdit, DatePicker, IndeterminateProgressRing, LineEdit, RadioButton, SearchLineEdit, Slider, SpinBox, SubtitleLabel, TimeEdit, TimePicker, ZhDatePicker
