# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_text(object):
    def setupUi(self, text):
        text.setObjectName("text2")
        text.resize(632, 484)
        self.LargeTitleLabel = LargeTitleLabel(text)
        self.LargeTitleLabel.setGeometry(QtCore.QRect(220, 190, 278, 54))
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")

        self.retranslateUi(text)
        QtCore.QMetaObject.connectSlotsByName(text)

    def retranslateUi(self, text):
        _translate = QtCore.QCoreApplication.translate
        text.setWindowTitle(_translate("text", "Form"))
        self.LargeTitleLabel.setText(_translate("text", "插件测试2"))
from qfluentwidgets import LargeTitleLabel
